inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'test/fixtures/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'cookbook/**/*'
    - 'Gemfile'
    - 'bin/*'
    - 'Guardfile'
    - 'config/puma.rb'
    - 'config/deploy.rb'
    - 'habitat/**/*'
    - 'lib/import/*'
    - 'lib/tasks/*.rake'
  TargetRubyVersion: '2.4'

# Offense count: 58
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 176
Style/Documentation:
  Enabled: false

# Offense count: 1
Style/Lambda:
  Enabled: false

# # Offense count: 1
# # Configuration parameters: NamePrefix, NamePrefixBlacklist.
# Style/PredicateName:
#   Enabled: false


# Offense count: 2
# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: false

StringLiterals:
  Enabled: false

NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
