inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'cookbook/**/*'
    - 'Gemfile'
    - 'bin/*'
    - 'Guardfile'
