development:
  port: 9315
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
  max_matches: 10000
  wordforms: config/wordforms.txt
test:
  port: 9315
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
  wordforms: config/wordforms.txt
production:
  address: localhost 
  port: 9315
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
  max_matches: 10000
  wordforms: config/wordforms.txt
