#!/usr/bin/env bash

hook=`readlink $0`
hook_path=`dirname ${hook}`
APP_PATH="${hook_path}/.."

export REPO_PATH=`pwd`

eval "$(rbenv init -)"
repo_script="${APP_PATH}/script/repo-update-hook.rb"
echo "Updating repo archive"
nohup $APP_PATH/script/rails runner "${repo_script}" 2>&1 &
