#!/usr/bin/env bash

hook=`readlink $0`
hook_path=`dirname ${hook}`
APP_PATH="${hook_path}/.."

export REPO_PATH=`pwd`

. "${APP_PATH}/config/git_hooks_env"
env

repo_script="${APP_PATH}/script/repo-update-hook.rb"
echo "Updating repo archive"
nohup $APP_PATH/script/rails runner "${repo_script}" > lastrun.log 2>&1 &
