---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[glynx_application::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: datamount
    run_list:
      - recipe[glynx_application::datamount]
    verifier:
      inspec_tests:
        - test/smoke/datamount
    attributes:
      glynx:
        datamount:
          device: 'pod3.gina.alaska.edu:/gvolnssi_silo'
          fstype: 'glusterfs'
