---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 12.19.36
verifier:
  name: inspec

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[glynx_application::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: datamount
    run_list:
      - recipe[glynx_application::datamount]
    verifier:
      inspec_tests:
        - test/smoke/datamount
    attributes:
      glynx:
        datamount:
          device: 'pod3.gina.alaska.edu:/gvolnssi_silo'
          fstype: 'glusterfs'
  - name: habitat
    run_list:
      - recipe[glynx_application::datamount]
      - recipe[glynx_application::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      glynx:
        deploy_method: habitat
        datamount:
          device: 'pod3.gina.alaska.edu:/gvolnssi_silo'
          fstype: 'glusterfs'
