name 'glynx-development'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cookbook'
long_description 'Installs/Configures cookbook'
version '0.1.0'

depends 'glynx_application'
depends 'glynx_database'
depends 'glynx_elasticsearch'
depends 'database'
depends 'postgresql'
