name 'glynx-development'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cookbook'
long_description 'Installs/Configures cookbook'
version '0.1.0'

depends 'gina-glynx-roles', '~> 2.0'
depends 'postgresql', '>= 6.0.1'
depends 'yum'
