# -*- mode: ruby -*-
# vi: set ft=ruby :
DEVVM_IP = '192.168.222.225'

Vagrant.configure('2') do |config|
  config.vm.hostname = 'glynx-development'

  config.vm.box = 'chef/centos-6.6'
  # config.vm.box_url = 'https://atlas.hashicorp.com/chef/boxes/centos-6.6/versions/1.0.0/providers/virtualbox.box'

  config.vm.network :private_network, ip: DEVVM_IP

  config.vm.synced_folder '../', '/www/glynx/current'
  # type: "rsync", rsync__exclude: [".git/", "cookbook/", '.kitchen/', '.gems/'],
  # rsync__args: ["--verbose", "--archive", "-z"],
  # rsync__auto: true

  config.vm.provider :virtualbox do |vb|
    # vb.gui = true
    vb.customize ['modifyvm', :id, '--memory', '4096']
    vb.customize ['modifyvm', :id, '--cpus', '2']
  end

  # if Vagrant.has_plugin?('vagrant-cachier')
  #   config.cache.scope  = :box
  # end

  config.berkshelf.enabled = false
  # config.chef_zero.enabled = true
  # config.chef_zero.chef_repo_path = '../glynx-dev'
  config.omnibus.chef_version = '12.3.0'

  # Force ip4/6 requests to be made seperatly
  # config.vm.provision :shell, inline: 'if [ ! $(grep single-request-reopen /etc/sysconfig/network) ]; then echo RES_OPTIONS=single-request-reopen >> /etc/sysconfig/network && service network restart; fi'

  config.vm.provision :chef_zero do |chef|
    chef.data_bags_path = "test/integration/data_bags"
    chef.json = {
      deploy: {
        environment: 'development',
        action: 'nothing',
        precompile_assets: false,
        service_static_assets: false
      },
      app: {
        data_bag: 'glynx_development',
        user: 'vagrant',
        group: 'vagrant'
      },
      postgresql: {
        password: {
          postgres: "wombats"
        }
      }
    }

    chef.run_list = [
      'recipe[glynx-development::default]'
    ]
  end
end
